// 画面尺寸
export function getDpiList() {
  return [
    {
        "SecondLabel": "changyongbili",
        "KeyWord2": "常用比例",
        "options": "正方形",
        "width": "1",
        "height": "1",
    },
    {
        "SecondLabel": null,
        "KeyWord2": "常用比例",
        "options": "3:2 / 1920:1280",
        "width": "3",
        "height": "2",
    },
    {
        "SecondLabel": null,
        "KeyWord2": "常用比例",
        "options": "4:3",
        "width": "4",
        "height": "3",
    },
    {
        "SecondLabel": null,
        "KeyWord2": "常用比例",
        "options": "9:16",
        "width": "9",
        "height": "16",
    },
    {
        "SecondLabel": "Xianshiqichicun",
        "KeyWord2": "显示器尺寸",
        "options": "1080P",
        "width": "1920",
        "height": "1080",
    },
    {
        "SecondLabel": null,
        "KeyWord2": "显示器尺寸",
        "options": "2K",
        "width": "2560",
        "height": "1440",
    },
    {
        "SecondLabel": null,
        "KeyWord2": "显示器尺寸",
        "options": "4K",
        "width": "4096",
        "height": "2160",
    },
    {
        "SecondLabel": "Yidongshebei",
        "KeyWord2": "移动设备",
        "options": "iPhone14 pro",
        "width": "1284",
        "height": "2778",
    },
    {
        "SecondLabel": null,
        "KeyWord2": "移动设备",
        "options": "iPhone14",
        "width": "1170",
        "height": "2532",
    },
    {
      "options": '自定义',
    }
  ]
}

// 作画参数
export function getParamslist() {
  return [
    {
      options: "测试模型", 
      type: "none",
      describe: "使用新的通用艺术测试模式。你得到两个使用正方形纵横比的图像；或者只是一个具有非方形纵横比的。",
      parameter: "--test",
      min: "",
      max: "",
      gap: "",
      option:"",
      checked: false, // 默认选中
    },
    {
      options: "现实主义照片", 
      type: "none",
      describe: "使用新的照片现实主义测试模式。您使用正方形宽高比获得两张图像；或者只有一张非正方形宽高比的图像。",
      parameter: "--testp",
      min: "",
      max: "",
      gap: "",
      option:"",
      checked: false,
    },
    {
      options: "图像重量", 
      type: "drag",
      describe: "默认图像权重为 0.25。Midjourney 仅支持单个图片权重参数，并且您必须至少有一个图片提示。",
      parameter: "--iw",
      min: "-10",
      max: "10",
      gap: "0.25",
      option: 0,
      checked: false,
    },
    {
      options: "算法选择", 
      type: "selector",
      describe: "设置Midjourney引擎的版本。在旧版本中，面孔、场景和生物更扭曲，一切都更抽象。",
      parameter: "--v",
      min: "",
      max: "",
      gap: "",
      option: [1, 2, 3],
      value: 1,
      index: 0,
      checked: false,
    },
    {
      options: "质量", 
      type: "selector",
      describe: "让你或多或少地给算法思考时间。它还会改变图像的成本。",
      parameter: "--q",
      min: "",
      max: "",
      gap: "",
      option: [0.25, 0.5, 1, 2, 5],
      value: 1,
      index: 2,
      checked: false,
    },
    {
      options: "风格化", 
      type: "drag",
      describe: "625将其关闭，建议经验丰富的用户使用1250，默认为2500，而20000+意味着非常强大的风格化。",
      parameter: "--s",
      min: "625",
      max: "60000",
      gap: "25",
      option: 625,
      checked: false,
    },
    {
      options: "混乱", 
      type: "drag",
      describe: "让画面更加混乱，变得更加抽象。",
      parameter: "--chaos",
      min: "0",
      max: "100",
      gap: "1",
      option: 1,
      checked: false,
    },
    {
      options: "停止", 
      type: "percentage", // drag
      describe: "早点停止这个过程。使用较低的百分比来避免添加太多细节，或将其设置为100%以像往常一样完成渲染。",
      parameter: "--stop",
      min: "10",
      max: "100",
      gap: "10",
      option: 10,
      checked: false,
    },
    {
      options: "减少细节", 
      type: "none",
      describe: "Upscaler时添加的细节相对变少，更接近预生成的图片。",
      parameter: "--uplight",
      min: "",
      max: "",
      gap: "",
      option:"",
      checked: false,
    },
    {
      options: "Beta升级器", 
      type: "none",
      describe: "干净、流畅和微妙的高分辨率升级。在/relax模式下工作。",
      parameter: "--upbeta",
      min: "",
      max: "",
      gap: "",
      option:"",
      checked: false,
    },
    {
      options: "保存进度视频", 
      type: "none",
      describe: "您必须使用（信封）进行反应才能获取视频链接。",
      parameter: "--video",
      min: "",
      max: "",
      gap: "",
      option:"",
      checked: false,
    },
    {
      options: "随机种子", 
      type: "textbox",
      describe: "设定一张图像的种子数，下次随机生成时引用它让画面和上次生成的结果更接近。",
      parameter: "--seed",
      min: "",
      max: "",
      gap: "",
      option:"",
      checked: false,
    },
  
    {
      options: "创意模式", 
      type: "none",
      describe: "会使结果更有创意，通常也会更混乱。",
      parameter: "--creative",
      min: "",
      max: "",
      gap: "",
      option:"",
      checked: false,
    },
    {
      options: "无缝纹理", 
      type: "none",
      describe: "将创建一个可以放置在自身旁边的可平铺纹理，而不会在图像副本之间创建明显的接缝、连接或边界。",
      parameter: "--tile",
      min: "",
      max: "",
      gap: "",
      option:"",
      checked: false,
    },
  ]
}
